
DATABASE_COL_INDEX_REAL_NAME = 1
DATABASE_COL_INDEX_ALT_NAMES = 3
DATABASE_COL_INDEX_GEO_LAT = 4
DATABASE_COL_INDEX_GEO_LONG = 5

SETTING_LOCATION_DB_NAMES_FILEPATH_KEY = "db_location_names_filepath"
SETTING_LOCATION_DB_MAPPERS_FILEPATH_KEY = "db_location_mapper_filepath"
SETTING_LOCATION_ACCEPTANCE_MIN_THRESHOLD = "location_acceptance_threshold"
