
EAVESDROP_DATA_PRE_PROCESSOR_GLM_MODEL_FILE_NAME = "textBranchNorm.h5"
EAVESDROP_DATA_PRE_PROCESSOR_GLM_PROCESSORS_FILE_NAME = "processors.obj"
EAVESDROP_DATA_PRE_PROCESSOR_GLM_VARS_FILE_NAME = "vars.obj"
