TASKS_STRUCT_FILE_FILENAME = "struct.json"
TASKS_STRUCT_FILE_PROP_DEP_DIRS = "dependency_directories"
TASKS_STRUCT_FILE_PROP_EXECUTORS = "executors"
TASKS_STRUCT_FILE_PROP_EXECUTORS_NAMESPACE = "namespace"
TASKS_STRUCT_FILE_PROP_EXECUTORS_CLASS = "class"
TASKS_STRUCT_FILE_PROP_EXECUTORS_PARAMS = "parameters"

TASKS_STRUCT_FILE_BASIC_PROPERTY_KEYS = [
    TASKS_STRUCT_FILE_PROP_DEP_DIRS,
    TASKS_STRUCT_FILE_PROP_EXECUTORS,
]

TASKS_DEPS_FILE_FILENAME = "dependencies.json"
TASKS_DEPS_FILE_PROP_DEP_NAME = "name"
TASKS_DEPS_FILE_PROP_DEP_VERSION = "version"

PROCESSES_STRUCT_FILE_FILENAME = "struct.json"
PROCESSES_STRUCT_FILE_PROP_DEP_DIRS = "dependency_directories"
PROCESSES_STRUCT_FILE_PROP_PROCESSES = "processes"
PROCESSES_STRUCT_FILE_PROP_PROCESSES_NAMESPACE = "namespace"
PROCESSES_STRUCT_FILE_PROP_PROCESSES_CLASS = "class"
PROCESSES_STRUCT_FILE_PROP_PROCESSES_PARAMS = "parameters"

PROCESSES_STRUCT_FILE_BASIC_PROPERTY_KEYS = [
    PROCESSES_STRUCT_FILE_PROP_DEP_DIRS,
    PROCESSES_STRUCT_FILE_PROP_PROCESSES,
]

PROCESSES_DEPS_FILE_FILENAME = "dependencies.json"
PROCESSES_DEPS_FILE_PROP_DEP_NAME = "name"
PROCESSES_DEPS_FILE_PROP_DEP_VERSION = "version"
