
ARG_EAVESDROP_MODE_STATUS = "eavesdrop_mode_status"
ARG_EAVESDROP_MODE_SAVE_INTERVAL = "eavesdrop_mode_save_interval"
ARG_EAVESDROP_MODE_SAVE_FOLDER_PATH = "eavesdrop_mode_save_folder_path"

VALUE_EAVESDROP_MODE_STATUS_ALLOWED = 1
VALUE_EAVESDROP_MODE_STATUS_NOT_ALLOWED = 0
